services:
  - type: web
    name: rene-kolednik-portfolio-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
