import { Platform, StyleSheet } from "react-native";

import { fonts, palette, shadow } from "../../../lib/theme";

export const styles = StyleSheet.create({
  outer: {
    width: "100%",
  },
  stickyFrame: {
    justifyContent: "center",
    paddingTop: 14,
    paddingBottom: 16,
  },
  scene: {
    position: "relative",
    minHeight: 790,
    justifyContent: "flex-start",
    paddingTop: 44,
  },
  sceneCompact: {
    minHeight: 900,
    justifyContent: "flex-start",
    paddingTop: 26,
  },
  orbitBackdrop: {
    ...StyleSheet.absoluteFillObject,
    overflow: "visible",
  },
  orbitInteractionLayer: {
    ...StyleSheet.absoluteFillObject,
    ...(Platform.OS === "web"
      ? {
          touchAction: "pan-y",
        }
      : {}),
  },
  orbitBackdropWide: {
    top: -14,
    bottom: 0,
  },
  orbitBackdropCompact: {
    top: 108,
  },
  orbitGlow: {
    position: "absolute",
    right: -40,
    top: -56,
    width: 900,
    height: 900,
    borderRadius: 999,
    backgroundColor: "rgba(152, 37, 152, 0.08)",
  },
  orbitGlowSecondary: {
    position: "absolute",
    right: 190,
    top: 74,
    width: 430,
    height: 430,
    borderRadius: 999,
    backgroundColor: "rgba(228, 145, 201, 0.06)",
  },
  orbitPath: {
    position: "absolute",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(152, 37, 152, 0.2)",
    borderRadius: 999,
    opacity: 0.42,
    transform: [{ rotate: "15deg" }],
  },
  orbitPathWide: {
    width: 1140,
    height: 590,
    left: "76%",
    top: "44%",
    marginLeft: -570,
    marginTop: -295,
  },
  orbitPathCompact: {
    width: 800,
    height: 390,
    left: "58%",
    top: "49%",
    marginLeft: -400,
    marginTop: -195,
  },
  overlayPanel: {
    position: "relative",
    zIndex: 20,
    width: "100%",
    maxWidth: 680,
    paddingTop: 0,
    paddingBottom: 32,
  },
  overlayPanelCompact: {
    maxWidth: "100%",
    paddingRight: 20,
  },
  contentCard: {
    width: "100%",
    maxWidth: 700,
    paddingHorizontal: 38,
    paddingVertical: 34,
    borderRadius: 38,
    backgroundColor: "rgba(255, 255, 255, 0.42)",
    borderColor: "rgba(255, 255, 255, 0.28)",
    ...(Platform.OS === "web"
      ? {
          backdropFilter: "blur(16px)",
          boxShadow: "0 18px 44px rgba(21, 23, 61, 0.08)",
        }
      : {}),
  },
  contentCardCompact: {
    paddingHorizontal: 24,
    paddingVertical: 24,
    borderRadius: 30,
  },
  availabilityPill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "rgba(152, 37, 152, 0.1)",
    marginBottom: 30,
  },
  availabilityPulse: {
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: palette.purple,
    borderWidth: 2,
    borderColor: "rgba(152, 37, 152, 0.14)",
  },
  availabilityText: {
    color: palette.purple,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.9,
    fontFamily: fonts.display,
  },
  name: {
    color: palette.navy,
    fontSize: 84,
    lineHeight: 84,
    fontWeight: "900",
    letterSpacing: -3.8,
    fontFamily: fonts.display,
  },
  nameCompact: {
    fontSize: 56,
    lineHeight: 58,
    letterSpacing: -2.5,
  },
  subtitle: {
    marginTop: 8,
    color: "rgba(21, 23, 61, 0.82)",
    fontSize: 26,
    lineHeight: 36,
    fontWeight: "500",
    fontFamily: fonts.display,
  },
  subtitleCompact: {
    fontSize: 21,
    lineHeight: 30,
  },
  subtitleAccent: {
    color: palette.purple,
    fontWeight: "700",
    fontFamily: fonts.display,
  },
  summary: {
    marginTop: 18,
    color: palette.muted,
    fontSize: 16,
    lineHeight: 30,
    fontFamily: fonts.display,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 22,
  },
  heroChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  heroChipDark: {
    backgroundColor: palette.navy,
  },
  heroChipPurple: {
    backgroundColor: "rgba(152, 37, 152, 0.18)",
  },
  heroChipPink: {
    backgroundColor: "rgba(228, 145, 201, 0.22)",
  },
  heroChipText: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    fontFamily: fonts.display,
  },
  heroChipTextLight: {
    color: "#FFFFFF",
  },
  heroChipTextDark: {
    color: palette.navy,
  },
  ctaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    marginTop: 28,
  },
  primaryCta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 22,
    paddingVertical: 15,
    borderRadius: 18,
    backgroundColor: palette.navy,
  },
  primaryCtaText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
    fontFamily: fonts.display,
  },
  primaryCtaArrow: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    fontFamily: fonts.display,
  },
  secondaryCta: {
    paddingHorizontal: 22,
    paddingVertical: 15,
    borderRadius: 18,
  },
  secondaryCtaText: {
    color: palette.navy,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: fonts.display,
  },
  orbitCardFrame: {
    position: "absolute",
    padding: 5,
    borderRadius: 34,
    backgroundColor: "rgba(255,255,255,0.66)",
    borderWidth: 1,
    borderColor: "rgba(152, 37, 152, 0.08)",
    ...shadow,
    ...(Platform.OS === "web"
      ? {
          backdropFilter: "blur(8px)",
        }
      : {}),
  },
  orbitCardFrameMotion: {
    ...(Platform.OS === "web"
      ? {
          transitionDuration: "520ms",
          transitionProperty: "transform, opacity, filter",
          transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
          willChange: "transform, opacity, filter",
        }
      : {}),
  },
  orbitCardInner: {
    flex: 1,
    position: "relative",
    justifyContent: "space-between",
    padding: 30,
    borderRadius: 29,
    overflow: "hidden",
  },
  orbitCardInnerDark: {
    backgroundColor: palette.navy,
  },
  orbitCardInnerSoft: {
    backgroundColor: "rgba(228, 145, 201, 0.28)",
    borderWidth: 1,
    borderColor: "rgba(152, 37, 152, 0.12)",
  },
  orbitCardInnerLight: {
    backgroundColor: "rgba(255,255,255,0.94)",
    borderWidth: 1,
    borderColor: "rgba(21,23,61,0.08)",
  },
  iconBadge: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  iconBadgeDark: {
    backgroundColor: "rgba(152, 37, 152, 0.2)",
  },
  iconBadgeSoft: {
    backgroundColor: "rgba(152, 37, 152, 0.14)",
  },
  iconBadgeLight: {
    backgroundColor: "rgba(152, 37, 152, 0.12)",
  },
  orbitCardMediaWrap: {
    position: "relative",
    minHeight: 246,
    marginBottom: 8,
    borderRadius: 26,
    overflow: "hidden",
  },
  orbitCardMediaImage: {
    width: "100%",
    height: 246,
    borderRadius: 26,
  },
  orbitCardMediaImageSpeedBump: {
    ...(Platform.OS === "web"
      ? {
          objectPosition: "center 18%",
        }
      : {}),
  },
  orbitCardFloatingBadge: {
    position: "absolute",
    top: -24,
    left: -24,
    zIndex: 5,
    width: 96,
    height: 96,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.96)",
    borderWidth: 1,
    borderColor: "rgba(228, 145, 201, 0.22)",
    ...(Platform.OS === "web"
      ? {
          boxShadow: "0 18px 38px rgba(21, 23, 61, 0.18)",
        }
      : {}),
  },
  orbitControlDock: {
    position: "absolute",
    right: -48,
    top: "50%",
    zIndex: 30,
    transform: [{ translateY: -40 }],
  },
  orbitControlDockCompact: {
    right: -12,
    top: "50%",
    transform: [{ translateY: -34 }],
  },
  orbitControlButton: {
    width: 80,
    height: 80,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.purple,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.26)",
    ...shadow,
    ...(Platform.OS === "web"
      ? {
          backdropFilter: "blur(14px)",
          transitionDuration: "180ms",
          transitionProperty: "transform, box-shadow, background-color",
          transitionTimingFunction: "ease-out",
          boxShadow: "0 24px 46px rgba(152, 37, 152, 0.34)",
        }
      : {}),
  },
  orbitControlButtonCompact: {
    width: 68,
    height: 68,
    borderRadius: 24,
  },
  orbitCardContentLayer: {
    flex: 1,
    justifyContent: "space-between",
    zIndex: 2,
  },
  orbitGhostMask: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    width: "48%",
    alignItems: "flex-end",
    justifyContent: "center",
    overflow: "hidden",
    zIndex: 0,
  },
  orbitGhostIcon: {
    opacity: 1,
  },
  orbitGhostFigureWrap: {
    width: 214,
    height: "88%",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  assistantGhostFrame: {
    width: 244,
    height: 404,
    position: "relative",
  },
  assistantGhostCap: {
    position: "absolute",
    top: 62,
    right: 18,
    width: 124,
    height: 66,
    borderTopLeftRadius: 62,
    borderTopRightRadius: 62,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
  },
  assistantGhostHead: {
    position: "absolute",
    top: 108,
    right: 8,
    width: 172,
    height: 172,
    borderWidth: 16,
    borderRadius: 30,
  },
  assistantGhostEyeLeft: {
    position: "absolute",
    top: 164,
    right: 106,
    width: 30,
    height: 30,
    borderRadius: 999,
  },
  assistantGhostEyeRight: {
    position: "absolute",
    top: 164,
    right: 48,
    width: 30,
    height: 30,
    borderRadius: 999,
  },
  assistantGhostMouth: {
    position: "absolute",
    top: 214,
    right: 58,
    width: 72,
    height: 18,
    borderRadius: 4,
  },
  assistantGhostSideTab: {
    position: "absolute",
    top: 142,
    right: 168,
    width: 46,
    height: 72,
    borderTopLeftRadius: 22,
    borderBottomLeftRadius: 22,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
  vendingGhostFrame: {
    width: 248,
    height: 430,
    position: "relative",
  },
  vendingGhostBody: {
    position: "absolute",
    right: 18,
    top: 28,
    width: 166,
    height: 328,
    borderWidth: 1,
    borderRadius: 28,
  },
  vendingGhostTopStrip: {
    position: "absolute",
    right: 34,
    top: 46,
    width: 134,
    height: 26,
    borderRadius: 13,
  },
  vendingGhostBrandBadge: {
    position: "absolute",
    right: 74,
    top: 84,
    width: 54,
    height: 18,
    borderWidth: 1,
    borderRadius: 9,
  },
  vendingGhostWindow: {
    position: "absolute",
    right: 98,
    top: 114,
    width: 62,
    height: 172,
    borderWidth: 1,
    borderRadius: 18,
  },
  vendingGhostShelfOne: {
    position: "absolute",
    right: 109,
    top: 148,
    width: 40,
    height: 6,
    borderRadius: 999,
  },
  vendingGhostShelfTwo: {
    position: "absolute",
    right: 109,
    top: 178,
    width: 40,
    height: 6,
    borderRadius: 999,
  },
  vendingGhostShelfThree: {
    position: "absolute",
    right: 109,
    top: 208,
    width: 40,
    height: 6,
    borderRadius: 999,
  },
  vendingGhostShelfFour: {
    position: "absolute",
    right: 109,
    top: 238,
    width: 40,
    height: 6,
    borderRadius: 999,
  },
  vendingGhostShelfFive: {
    position: "absolute",
    right: 109,
    top: 268,
    width: 40,
    height: 6,
    borderRadius: 999,
  },
  vendingGhostProductA: {
    position: "absolute",
    right: 119,
    top: 128,
    width: 18,
    height: 12,
    borderRadius: 6,
  },
  vendingGhostProductB: {
    position: "absolute",
    right: 112,
    top: 158,
    width: 14,
    height: 14,
    borderRadius: 4,
  },
  vendingGhostProductC: {
    position: "absolute",
    right: 123,
    top: 188,
    width: 10,
    height: 14,
    borderRadius: 5,
  },
  vendingGhostProductD: {
    position: "absolute",
    right: 112,
    top: 218,
    width: 16,
    height: 12,
    borderRadius: 5,
  },
  vendingGhostProductE: {
    position: "absolute",
    right: 124,
    top: 246,
    width: 12,
    height: 14,
    borderRadius: 6,
  },
  vendingGhostProductF: {
    position: "absolute",
    right: 114,
    top: 278,
    width: 18,
    height: 10,
    borderRadius: 5,
  },
  vendingGhostPanel: {
    position: "absolute",
    right: 42,
    top: 114,
    width: 38,
    height: 172,
    borderWidth: 1,
    borderRadius: 16,
  },
  vendingGhostDisplay: {
    position: "absolute",
    right: 50,
    top: 128,
    width: 22,
    height: 12,
    borderRadius: 6,
  },
  vendingGhostKeypad: {
    position: "absolute",
    right: 48,
    top: 154,
    width: 22,
    height: 52,
    borderWidth: 1,
    borderRadius: 6,
  },
  vendingGhostCoinSlot: {
    position: "absolute",
    right: 48,
    top: 220,
    width: 24,
    height: 8,
    borderRadius: 4,
  },
  vendingGhostHandle: {
    position: "absolute",
    right: 60,
    top: 238,
    width: 8,
    height: 28,
    borderRadius: 999,
  },
  vendingGhostBase: {
    position: "absolute",
    right: 36,
    top: 304,
    width: 130,
    height: 38,
    borderWidth: 1,
    borderRadius: 14,
  },
  vendingGhostDispenseDoor: {
    position: "absolute",
    right: 68,
    top: 314,
    width: 66,
    height: 16,
    borderWidth: 1,
    borderRadius: 8,
  },
  plantGhostFrame: {
    width: 248,
    height: 420,
    position: "relative",
  },
  plantGhostLeafBackLeft: {
    position: "absolute",
    right: 126,
    top: 60,
    width: 64,
    height: 138,
    borderWidth: 1,
    borderTopLeftRadius: 60,
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 60,
    borderBottomRightRadius: 60,
    transform: [{ rotate: "-34deg" }],
  },
  plantGhostLeafBackRight: {
    position: "absolute",
    right: 40,
    top: 62,
    width: 66,
    height: 144,
    borderWidth: 1,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 60,
    borderBottomLeftRadius: 60,
    borderBottomRightRadius: 60,
    transform: [{ rotate: "32deg" }],
  },
  plantGhostStemLeft: {
    position: "absolute",
    right: 118,
    top: 172,
    width: 8,
    height: 70,
    borderRadius: 999,
    transform: [{ rotate: "-12deg" }],
  },
  plantGhostStemRight: {
    position: "absolute",
    right: 106,
    top: 174,
    width: 8,
    height: 66,
    borderRadius: 999,
    transform: [{ rotate: "10deg" }],
  },
  plantGhostLeafFrontLeft: {
    position: "absolute",
    right: 118,
    top: 94,
    width: 52,
    height: 114,
    borderWidth: 1,
    borderTopLeftRadius: 52,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 52,
    borderBottomRightRadius: 52,
    transform: [{ rotate: "-18deg" }],
  },
  plantGhostLeafCenter: {
    position: "absolute",
    right: 88,
    top: 52,
    width: 54,
    height: 152,
    borderWidth: 1,
    borderTopLeftRadius: 54,
    borderTopRightRadius: 54,
    borderBottomLeftRadius: 54,
    borderBottomRightRadius: 54,
  },
  plantGhostLeafFrontRight: {
    position: "absolute",
    right: 54,
    top: 98,
    width: 50,
    height: 110,
    borderWidth: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 50,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    transform: [{ rotate: "18deg" }],
  },
  plantGhostPotRim: {
    position: "absolute",
    right: 46,
    top: 236,
    width: 144,
    height: 30,
    borderWidth: 1,
    borderRadius: 16,
  },
  plantGhostPotBody: {
    position: "absolute",
    right: 58,
    top: 256,
    width: 120,
    height: 102,
    borderWidth: 1,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
  },
  plantGhostPotBase: {
    position: "absolute",
    right: 78,
    top: 352,
    width: 80,
    height: 18,
    borderWidth: 1,
    borderRadius: 10,
  },
  orbitCardBody: {
    marginTop: 24,
    gap: 16,
  },
  orbitCardBodyWithMedia: {
    marginTop: 12,
  },
  orbitCardTitle: {
    fontSize: 48,
    lineHeight: 52,
    fontWeight: "900",
    fontFamily: fonts.display,
  },
  orbitCardTitleLight: {
    color: "#FFFFFF",
  },
  orbitCardTitleDark: {
    color: palette.navy,
  },
  orbitCardCopy: {
    fontSize: 15,
    lineHeight: 28,
    fontWeight: "500",
    fontFamily: fonts.display,
  },
  orbitCardCopyLight: {
    color: "rgba(255,255,255,0.72)",
  },
  orbitCardCopyDark: {
    color: palette.muted,
  },
  orbitCardOutcome: {
    fontSize: 14,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: fonts.display,
  },
  orbitCardOutcomeLight: {
    color: "rgba(255,255,255,0.9)",
  },
  orbitCardOutcomeDark: {
    color: palette.navy,
  },
  orbitCardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  orbitCardTagRow: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  orbitCardTagChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  orbitCardTagChipDark: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderColor: "rgba(255,255,255,0.12)",
  },
  orbitCardTagChipSoft: {
    backgroundColor: "rgba(255,255,255,0.34)",
    borderColor: "rgba(152, 37, 152, 0.14)",
  },
  orbitCardTagChipLight: {
    backgroundColor: "rgba(21,23,61,0.04)",
    borderColor: "rgba(21,23,61,0.08)",
  },
  orbitCardTag: {
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    fontFamily: fonts.display,
  },
  orbitCardTagLight: {
    color: palette.pink,
  },
  orbitCardTagSoft: {
    color: palette.purple,
  },
  orbitCardTagDark: {
    color: palette.purple,
  },
  projectLinkButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
  },
  projectLinkButtonDark: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderColor: "rgba(255,255,255,0.12)",
  },
  projectLinkButtonSoft: {
    backgroundColor: "rgba(255,255,255,0.3)",
    borderColor: "rgba(152, 37, 152, 0.14)",
  },
  projectLinkButtonLight: {
    backgroundColor: "rgba(21,23,61,0.04)",
    borderColor: "rgba(21,23,61,0.08)",
  },
  projectLinkButtonDisabled: {
    opacity: 0.45,
  },
  projectLinkText: {
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    fontFamily: fonts.display,
  },

  // ─── Phone layout ─────────────────────────────────────────────────────────
  phoneScene: {
    flexDirection: "column",
    paddingTop: 18,
    paddingBottom: 24,
    gap: 24,
    overflow: "visible",
  },
  phoneBgGlow: {
    position: "absolute",
    top: -40,
    right: -60,
    width: 280,
    height: 280,
    borderRadius: 999,
    backgroundColor: "rgba(152, 37, 152, 0.14)",
    ...(Platform.OS === "web"
      ? {
          filter: "blur(72px)",
        }
      : {}),
  },
  phoneCtaFull: {
    flex: 1,
    justifyContent: "center",
  },
  phoneCarouselWrap: {
    gap: 14,
  },
  phoneCarouselContent: {
    paddingHorizontal: 0,
  },
  phoneCarouselCard: {
    height: 240,
    borderRadius: 22,
    overflow: "hidden",
    position: "relative",
    backgroundColor: palette.navy,
    ...shadow,
  },
  phoneCarouselImage: {
    width: "100%",
    height: "100%",
  },
  phoneCarouselImageFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(152, 37, 152, 0.12)",
  },
  phoneCarouselOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 18,
    paddingTop: 36,
    paddingBottom: 16,
    backgroundColor: "rgba(21, 23, 61, 0.66)",
    gap: 4,
    ...(Platform.OS === "web"
      ? {
          backdropFilter: "blur(6px)",
        }
      : {}),
  },
  phoneCarouselTag: {
    color: palette.pink,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.4,
    textTransform: "uppercase",
    fontFamily: fonts.display,
  },
  phoneCarouselTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    fontFamily: fonts.display,
  },
  phoneCarouselLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
    alignSelf: "flex-start",
  },
  phoneCarouselLinkText: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    fontFamily: fonts.display,
  },
  dotRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "rgba(21, 23, 61, 0.16)",
    borderWidth: 1,
    borderColor: "rgba(21, 23, 61, 0.12)",
  },
  dotActive: {
    backgroundColor: palette.purple,
    borderColor: palette.purple,
    width: 20,
  },
});
